server:
  port: 9002
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/qiniuchat?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: hnit_server
      username: root
      password: "123456"
      authentication-database: admin
    redis:
      host: redis
      port: 6379
      password:
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
        shutdown-timeout: 100ms
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: Aa123456==
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: auto
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 3000
        multiplier: 2

# 其他配置保持不变
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qiniuai.chat.demos.web.entity.pojo

baidu:
  tts:
    app-id: 7080599
    api-key: rQVaLxr0BZn0xv8Ad6Nzzq70
    secret-key: AfdR5QpvqyWS07OL43WAMCCH1RtDk8g1
    default:
      voice: 0
      speed: 5
      pitch: 5
      volume: 5

xunfei:
  tts:
    app-id: eef954cd
    api-key: 4243b6cacf6c7bff27a16b333cffe247
    api-secret: N2E0Y2U1NWIzYWQ3MmNjMGIyZGU5YWFh
    host-url: wss://spark-api.xf-yun.com/v4.0/chat
    role-mapping:
      harry-potter: "en_hp"
      socrates: "en_socrates"
      default: "xiaoyan"

qiniu:
  kodo:
    access-key: hHXoW4db7Oumj1B_0EwkmmV7BGVcAQxgbo1y-w7q
    secret-key: ZJ7NpuflHtI8fX4DXwWtZCbLynQ1e0n4ryv7AVuM
    bucket-name: hnit-qiniu
    domain: t31wwjckj.sabkt.gdipper.com
    base-path: tts-audio/

third-party:
  aliyun:
    access-key-id: LTAI5tFQZ7WbmkPzioKZfDd7
    access-key-secret: amLpi3qgnYGiNUHejETMX2ssqoGVPN
    region-id: cn-shanghai
    asr:
      app-key: sk-91e9869d987d4dccaf03889cc6c33871
      url: https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/asr
      model: paraformer-realtime-8k-v2
      format: mp3
      sample-rate: 8000
      timeout: 30000
    tts:
      app-key: sk-91e9869d987d4dccaf03889cc6c33871
      url: https://dashscope.aliyuncs.com/api/v1/services/audio/speech_synthesis
      voice: xiaoyun
      format: mp3
      sample-rate: 16000
      model: qwen3-tts-v1
      timeout: 30000

  deepseek:
    url: https://api.deepseek.com/v1/chat/completions
    api-key: sk-c620dc51a0394439a300c3d257fa435f
    model: deepseek-chat
    timeout: 60000
    max-tokens: 1024
    temperature: 0.7

  iflytek:
    app-id: eef954cd
    api-key: 4243b6cacf6c7bff27a16b333cffe247
    api-secret: N2E0Y2U1NWIzYWQ3MmNjMGIyZGU5YWFh
    voice-conversion:
      url: https://api.xfyun.cn/v1/service/v1/tts/voice_conversion

ali:
  audio:
    asr:
      api-key: sk-95513ded49764ba6a533d427797b6f20
    tts:
      api-key: sk-95513ded49764ba6a533d427797b6f20

app:
  audio:
    temp-dir: /app/temp-audio
    chunk-size: 1024
    max-duration-seconds: 60
    clean-expired-files-cron: "0 0 */1 * * ?"

  cache:
    role-info-expire-hours: 24
    conversation-status-expire-minutes: 30

  websocket:
    endpoint: /ws/voice-call
    broker:
      prefix: /topic
      destination: /queue/voice-response

thread-pool:
  asr:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: asr-executor-

  llm:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: llm-executor-

  tts:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: tts-executor-

  voice-conversion:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: voice-conversion-executor-

rabbitmq:
  queues:
    audio-merge: audio.merge.queue
    asr-task: asr.task.queue
    llm-task: llm.task.queue
    tts-task: tts.task.queue
    voice-conversion-task: voice.conversion.task.queue
    websocket-send: websocket.send.queue

  exchanges:
    task-exchange: task.exchange

  routing-keys:
    audio-merge: audio.merge.key
    asr-task: asr.task.key
    llm-task: llm.task.key
    tts-task: tts.task.key
    voice-conversion-task: voice.conversion.key
    websocket-send: websocket.send.key

audio:
  temp-dir: /app/temp-audio
  chunk-size: 1024
  max-duration: 60
  format: mp3
  sample-rate: 8000

logging:
  level:
    root: INFO
    com.qiniuai.chat.demos: DEBUG
  file:
    name: /app/logs/qiniu-ai-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 健康检查端点（确保在应用中启用）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always