server:
  port: 9002
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:154.41.93.132}:3306/qiniuchat?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: ${MONGO_HOST:154.41.93.132}
      port: 27017
      database: hnit_server
      username: ${MONGO_USER:root}
      password: ${MONGO_PASSWORD:}
      authentication-database: admin
    redis:
      host: ${REDIS_HOST:154.41.93.132}
      port: 6379
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
        shutdown-timeout: 100ms
  rabbitmq:
    host: ${RABBITMQ_HOST:154.41.93.132}
    port: 5672
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:}
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        prefetch: 1
        acknowledge-mode: auto
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 3000
        multiplier: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qiniuai.chat.demos.web.entity.pojo

baidu:
  tts:
    app-id: 7080599
    api-key: ${BAIDU_API_KEY:}
    secret-key: ${BAIDU_SECRET_KEY:}
    default:
      voice: 0
      speed: 5
      pitch: 5
      volume: 5

xunfei:
  tts:
    app-id: eef954cd
    api-key: ${XUNFEI_API_KEY:}
    api-secret: ${XUNFEI_API_SECRET:}
    host-url: wss://spark-api.xf-yun.com/v4.0/chat
    role-mapping:
      harry-potter: "en_hp"
      socrates: "en_socrates"
      default: "xiaoyan"

qiniu:
  kodo:
    access-key: ${QINIU_ACCESS_KEY:}
    secret-key: ${QINIU_SECRET_KEY:}
    bucket-name: hnit-qiniu
    domain: t31wwjckj.sabkt.gdipper.com
    base-path: tts-audio/

third-party:
  aliyun:
    access-key-id: ${ALIYUN_ACCESS_KEY:}
    access-key-secret: ${ALIYUN_SECRET:}
    region-id: cn-shanghai
    asr:
      app-key: ${ALIYUN_ASR_KEY:}
      url: https://nls-gateway.cn-shanghai.aliyuncs.com/stream/v1/asr
      model: paraformer-realtime-8k-v2
      format: mp3
      sample-rate: 8000
      timeout: 30000
    tts:
      app-key: ${ALIYUN_TTS_KEY:}
      url: https://dashscope.aliyuncs.com/api/v1/services/audio/speech_synthesis
      voice: xiaoyun
      format: mp3
      sample-rate: 16000
      model: qwen3-tts-v1
      timeout: 30000
  deepseek:
    url: https://api.deepseek.com/v1/chat/completions
    api-key: ${DEEPSEEK_API_KEY:}
    model: deepseek-chat
    timeout: 60000
    max-tokens: 1024
    temperature: 0.7
  iflytek:
    app-id: eef954cd
    api-key: ${IFLYTEK_API_KEY:}
    api-secret: ${IFLYTEK_API_SECRET:}
    voice-conversion:
      url: https://api.xfyun.cn/v1/service/v1/tts/voice_conversion

ali:
  audio:
    asr:
      api-key: ${ALI_AUDIO_KEY:}
    tts:
      api-key: ${ALI_AUDIO_KEY:}

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY:}
    accessKeySecret: ${OSS_SECRET:}
    bucketName: qiniuai
    customDomain: https://qiniuai.oss-cn-beijing.aliyuncs.com

app:
  audio:
    temp-dir: ./temp-audio
    chunk-size: 1024
    max-duration-seconds: 60
    clean-expired-files-cron: 0 0 */1 * * ?
  cache:
    role-info-expire-hours: 24
    conversation-status-expire-minutes: 30
  websocket:
    endpoint: /ws/voice-call
    broker:
      prefix: /topic
      destination: /queue/voice-response

thread-pool:
  asr:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: asr-executor-
  llm:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: llm-executor-
  tts:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: tts-executor-
  voice-conversion:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
    thread-name-prefix: voice-conversion-executor-

rabbitmq:
  queues:
    audio-merge: audio.merge.queue
    asr-task: asr.task.queue
    llm-task: llm.task.queue
    tts-task: tts.task.queue
    voice-conversion-task: voice.conversion.task.queue
    websocket-send: websocket.send.queue
  exchanges:
    task-exchange: task.exchange
  routing-keys:
    audio-merge: audio.merge.key
    asr-task: asr.task.key
    llm-task: llm.task.key
    tts-task: tts.task.key
    voice-conversion-task: voice.conversion.key
    websocket-send: websocket.send.key

audio:
  temp-dir: ./temp-audio
  chunk-size: 1024
  max-duration: 60
  format: mp3
  sample-rate: 8000

logging:
  level:
    root: INFO
    com.qiniu.chat.demos: DEBUG
  file:
    name: logs/qiniu-ai-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"