server:
  port: 9002 # 服务端口
  servlet:
    context-path: / # 上下文路径
spring:
  datasource:
    url: jdbc:mysql://154.41.93.132:3306/qiniuchat?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root  # 替换为你的用户名
    password: 123456  # 替换为你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      # MongoDB服务器地址
      host: 154.41.93.132
      # 端口号
      port: 27017
      # 数据库名称
      database: hnit_server
      # 认证信息（关键）
      username: root
      password: "123456"
      # 认证数据库（默认为admin，若用户名密码在其他数据库创建则需指定）
      authentication-database: admin
    redis:
      # Redis服务器地址（默认本地）
      host: 154.41.93.132
      # Redis服务器端口（默认6379）
      port: 6379
      # Redis密码（若未设置密码则留空）
      password:
      # 数据库索引（默认0，Redis支持16个数据库，从0开始）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 3000ms
      # 连接池配置（使用Lettuce，Spring Boot 2.x+默认客户端）
      lettuce:
        pool:
          # 最大连接数（默认8，根据服务器性能调整）
          max-active: 8
          # 最大空闲连接数（默认8）
          max-idle: 8
          # 最小空闲连接数（默认0）
          min-idle: 2
          # 连接池最大阻塞等待时间（毫秒，-1表示无限制）
          max-wait: 1000ms
        # 关闭超时时间（毫秒）
        shutdown-timeout: 100ms
mybatis:
  mapper-locations: classpath:mapper/*.xml  # mapper.xml 文件路径（如果用 XML 写 SQL）·
  type-aliases-package: com.qiniuai.chat.demos.web.entity.pojo  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线转驼峰自动映射

#百度tts配置
baidu:
  tts:
    app-id: 7080599
    api-key: rQVaLxr0BZn0xv8Ad6Nzzq70
    secret-key: AfdR5QpvqyWS07OL43WAMCCH1RtDk8g1
    default:
      voice: 0 # 默认发音人（0-女声，1-男声）
      speed: 5 # 默认语速（0-9）
      pitch: 5 # 默认音调（0-9）
      volume: 5 # 默认音量（0-9）
# 讯飞开放平台配置
xunfei:
  tts:
    app-id: {{.app_id}}
    api-key: {{.api_key}
    api-secret: {{.secret_key}}
    host-url: wss://tts-api.xfyun.cn/v2/tts
    # 预设角色映射（键为角色名，值为讯飞语音ID）
    role-mapping:
      harry-potter: "en_hp"
      socrates: "en_socrates"
      default: "xiaoyan"
qiniu:
  kodo:
    access-key: hHXoW4db7Oumj1B_0EwkmmV7BGVcAQxgbo1y-w7q
    secret-key: ZJ7NpuflHtI8fX4DXwWtZCbLynQ1e0n4ryv7AVuM
    bucket-name: hnit-wlwsys
    domain:
    base-path: tts-audio/ # 音频存储基础路径

logging:
  level:
    root: INFO # 根日志级别
    com.qiniu.chat.demos: DEBUG # 项目包日志级别
  file:
    name: logs/qiniu-ai-service.log # 日志文件路径
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 控制台日志格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # 文件日志格式
